create table public.project_gmail_messages (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  gmail_message_id text not null,
  gmail_thread_id text not null,
  sender_name text not null default '',
  sender_email text not null default '',
  recipient_emails text[] not null default '{}',
  subject text not null default '',
  body_text text not null default '',
  message_date timestamptz not null,
  direction text not null check (direction in ('incoming', 'outgoing')),
  has_attachments boolean not null default false,
  message_id_header text not null default '',
  references_header text not null default '',
  created_at timestamptz not null default now(),
  unique (project_id, gmail_message_id)
);

create index project_gmail_messages_project_date_idx
  on public.project_gmail_messages(project_id, message_date);

create table public.project_gmail_attachments (
  id bigint generated by default as identity primary key,
  project_id text not null references public.projects(id) on delete cascade,
  gmail_message_id text not null,
  gmail_attachment_id text,
  mime_part_id text not null,
  filename text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null default 0,
  download_status text not null default 'pending'
    check (download_status in ('pending', 'downloaded', 'skipped', 'renamed', 'failed')),
  saved_filename text,
  download_error text,
  downloaded_at timestamptz,
  created_at timestamptz not null default now(),
  unique (project_id, gmail_message_id, mime_part_id),
  foreign key (project_id, gmail_message_id)
    references public.project_gmail_messages(project_id, gmail_message_id)
    on delete cascade
);

create index project_gmail_attachments_pending_idx
  on public.project_gmail_attachments(project_id, download_status);

alter table public.project_gmail_messages enable row level security;
alter table public.project_gmail_attachments enable row level security;

create policy allow_authenticated_full_access_project_gmail_messages
  on public.project_gmail_messages for all to authenticated using (true) with check (true);

create policy allow_authenticated_full_access_project_gmail_attachments
  on public.project_gmail_attachments for all to authenticated using (true) with check (true);
